# Generated by Django 5.2.9 on 2025-12-05 08:39

import django.core.validators
import django.db.models.deletion
import document_builder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('data', models.JSONField(default=dict, verbose_name='Данные шаблона (блоки, zoom и т.д.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document_builder.models.source_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('parsed_content', models.JSONField(default=list, verbose_name='Результат парсинга (страницы с текстом)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='document_builder.documenttemplate', verbose_name='Привязанный шаблон')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
